---
title: "analise-cluster"
author: "pedro-hos@outlook.com"
date: "6/17/2021"
output: html_document
---

```{r}
library(tidyverse) #pacote para manipulacao de dados
library(cluster) #algoritmo de cluster
library(dendextend) #compara dendogramas
library(factoextra) #algoritmo de cluster e visualizacao
library(fpc) #algoritmo de cluster e visualizacao
library(gridExtra) #para a funcao grid arrange
library(readxl)

dados <- read.csv("alldata.csv")
rownames(dados) <- dados[,1]
dados <- dados[,3]

# Calculando Distância Euclediana

d <- dist(dados, method = "euclidean")
```

```{r}
#DEFININDO O CLUSTER A PARTIR DO METODO ESCOLHIDO
#metodos disponiveis "average", "single", "complete" e "ward.D"
hc1 <- hclust(d, method = "single" )
plot(hc1, cex = 0.6, hang = -1)
```

```{r}
hc2 <- hclust(d, method = "complete" )
plot(hc2, cex = 0.6, hang = -1)
```

```{r}
hc3 <- hclust(d, method = "average" )
plot(hc3, cex = 0.6, hang = -1)
```
```{r}
hc4 <- hclust(d, method = "ward.D" )
plot(hc4, cex = 0.6, hang = -1)
```

```{r}
rect.hclust(hc4, k = 2)
```
