---
title: "Urbam Deaths SJC"
author: "pedro-hos@outlook.com"
date: "06/06/2021"
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
library(ggrepel)
library(readr)
library(magrittr)
library(dplyr)
```

#Lendo 

```{r}
dados <- read.csv("alldata.csv")
dados$MONTH <- factor(dados$MONTH, levels = rev(c("JANEIRO", "FEVEREIRO", "MARCO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO")))
```

#Head
```{r}
head(dados)
```

#Tail
```{r}
tail(dados)
```
#Óbitos por Ano

```{r}
ggplotly(
  ggplot(data = dados) + 
    geom_bar(aes(x = YEAR)) + 
    labs(title = "Óbitos por ano segundo site da URBAM", 
         x = "Anos", y = "Óbitos", caption = "Período de 2016 à Junho de 2021") +
    theme_light()
)
```
```{r}
ggplotly(
  ggplot(data = dados) + 
    geom_bar(aes(fill = MONTH, x = YEAR)) + 
    labs(title = "Óbitos por ano segundo site da URBAM", 
         x = "Anos", y = "Óbitos", caption = "Período de 2016 à Junho de 2021") +
    theme_light()
)
```

```{r}
dados$RANGE_AGE = NA

dados$RANGE_AGE <- case_when( dados$AGE == 0 ~ "Natimorto",
                             (dados$AGE > 0 & dados$AGE <= 15) ~ "Jovens", 
                             (dados$AGE > 15 & dados$AGE <=64) ~ "Adultos",
                             (dados$AGE >= 65) ~ "Idosos")

#write.csv(dados, file="alldata.csv")

dados[,c("AGE", "RANGE_AGE")]
```

```{r}
graph <- ggplot(data = dados, aes(fill = RANGE_AGE, x = MONTH)) + 
    geom_bar(show.legend = TRUE) + 
    labs(title = "Óbitos por ano segundo site da URBAM", 
         x = "Anos", y = "Óbitos", caption = "Período de 2016 à Junho de 2021") +
    theme_light()

ggplotly(graph)
```
```{r}
mortes_range <- read.csv("mortes_range.csv")
graph <- ggplot(data = mortes_range, aes(fill = n_ranges, x = n_years, y=values)) + 
  geom_bar(position="dodge", stat="identity") + 
  labs(title = "Óbitos por range idade segundo site da URBAM", 
       x = "Anos", y = "Óbitos", caption = "Período de 2016 à Junho de 2021") +
  theme_light()

ggplotly(graph)
```